# rabbitmq-svc-nodeport.yml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: netflow
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: management
    port: 15672
    targetPort: 15672

