# web-svc-nodeport.yml
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: netflow
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP

