# clusters/production/apps.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netflow-apps
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: netflow-infrastructure
  path: ./apps/netflow/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: web-deployment
      namespace: netflow
    - apiVersion: apps/v1
      kind: Deployment
      name: rabbitmq
      namespace: netflow
    - apiVersion: apps/v1
      kind: Deployment
      name: scheduler
      namespace: netflow
    - apiVersion: apps/v1
      kind: Deployment
      name: worker
      namespace: netflow
